### ISSUE TITLE
any chance of the .sch files?

### ISSUE THREAD

**Issue by KeLaiFu** [PierreIsCoding/sdiy#1]
thanks for the nice list of sdiy modules, I am hoping to build a few in my spare time.
I noticed that the .pdf for the schematic has been made in kicad, would it be possible to upload the actual kicad file too? Since I would be copying the layout into kicad to work from it, just thought I'd ask :)

**Comment by PierreIsCoding** [comment]
Ha KeLaiFu. Thank you for your interest. I made the projects in Kicad indeed. I won't upload the Kicad files to github, because I like to have a conversation like this instead of people anonymously download the source files. I also don't made a few footprints, so until recently with Kicad 6 it is easy to share anyways. I send you a message on Discord (assuming its you). Let me know which projects you want to start first.

**Comment by KeLaiFu** [comment]
Thanks for the reply and I fully understand your reasons. 

I didn't contact you on discord, my account (or however it works) hasn't been used in a while, I will try and log in though, I have been meaning to for a while.

would be it possible to email me? clive.rowland(at)gmail.com

Thanks again, much appreciated
